/*CREATE USERS TABLE */
CREATE TABLE `users`(
`id` BIGINT NOT NULL AUTO_INCREMENT,
`firstname` VARCHAR(255) NOT NULL,
`lastname` VARCHAR(255) NOT NULL,
`email` VARCHAR(255) UNIQUE NOT NULL,
`password`VARCHAR(255) NOT NULL,
PRIMARY KEY (`id`)
);